name: coverage
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
      - name: Install goveralls
        run: go install github.com/mattn/goveralls@latest
      - name: Run tests
        run: go test -v -coverprofile=profile.cov ./...
      - name: Send coverage
        run: goveralls -coverprofile=profile.cov -reponame github.com/Roundaround/cva-go -repotoken ${{ secrets.COVERALLS_REPO_TOKEN }} -service=github