name: test
on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
      - name: Run tests
        run: go test ./...
  examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
      - name: Download dependencies
        working-directory: examples
        run: go mod download
      - name: Generate templ files
        working-directory: examples
        run: go tool templ generate
      - name: Run tests
        working-directory: examples
        run: go test ./...
